export class EventConstant {
  static GET_USERS = 'GET_USERS';
  static SEND_TEXT_CHAT = 'SEND_TEXT_CHAT';
  static GET_CHAT_TOPICS = 'GET_CHAT_TOPICS';
  static CREATE_CHAT_TOPIC = 'CREATE_CHAT_TOPIC';
  static GET_CHAT_HISTORY = 'GET_CHAT_HISTORY';
  static CHAT_SEEN = 'CHAT_SEEN';
  static UPDATE_CHAT_GROUP = 'UPDATE_CHAT_GROUP';
  static LEAVE_CHAT_GROUP = 'LEAVE_CHAT_GROUP';
  static CHANGE_CHAT_GROUP_AVATAR = 'CHANGE_CHAT_GROUP_AVATAR';
}
